sample_app/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/help', to: 'static_pages#help', as: 'helf'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
end

sample_app/app/models/user.rb
class User < ApplicationRecord
  validates :name, 
    presence: true, 
    length: { maximum: 50 }
  validates :email, 
    presence: true, 
    length: { maximum: 255 },
    uniqueness: true,
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password,
    length: { minimum: 6 },
    presence: true

  before_save { self.email = email.downcase }

  has_secure_password
end

sample_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

sample_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: login_params[:email].downcase)
    if user && user.authenticate(login_params[:password])
      flash.now[:success] = "Weclome, #{user.name}!"
      render 'new', status: :ok
    else
      flash.now[:danger] = "Email and password combination not recognized."
      render 'new', status: :unauthorized
    end
  end

  def destroy
  end

  def login_params
    params.require(:session).permit(:email, :password)
  end
end

sample_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

sample_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "WELCOME TO THE INTERNET!"
      redirect_to(@user)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

sample_app/app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(pageTitle)
    return "MICROPOSTS" if pageTitle.blank?
    "#{pageTitle} | MP"
  end
end

sample_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

sample_app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

sample_app/app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 80)
    grav_id = Digest::MD5::hexdigest(user.email.downcase)
    grav_url = "https://secure.gravatar.com/avatar/#{grav_id}?s=#{size}"
    image_tag(grav_url, alt: user.name, class: "gravatar")
  end
end

sample_app/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",  about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

sample_app/app/views/layouts/_head.html.erb
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta charset="utf-8">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= favicon_link_tag asset_path('rails.svg')%>
</head>

sample_app/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "||| MICROPOSTS |||", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", helf_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Log in", "#" %></li>
      </ul>
    </nav>
  </div>
</header>

sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render "layouts/head" %>

  <body style="font-family: consolas">
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>" data-test-id="main-flash">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

sample_app/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <div>
<% end %>

sample_app/app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div>
  <h1>ABOUT</h1>
  <p>Microposts is actually a pretty useless application. Its social media, but without the social part.</p>
<div>

sample_app/app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://www.railstutorial.org/contact">contact page</a>.
</p>

sample_app/app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<div>
  <h1>HELP</h1>
  <p>Need help? Read <a href="https://github.com/benCoomes/rails-tutorial/tree/main/sample_app">the source</a>.</p>
<div>

sample_app/app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>M I C R O P O S T S</h1>
  <h2>For when your ideas are tiny.</h2>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.svg", alt: "Rails logo", width: "200"), "https://rubyonrails.org" %>

sample_app/app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

sample_app/app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for(@user)%> 
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>